version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    ports:
      - 80:80
    links:
      - php
  php:
    image: chialab/php:7.2-fpm
    volumes:
      - ./:/var/www/html:cached
    links:
      - postgres
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
  postgres:
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_dev_db
    ports:
      - 5432:5432
